# Use Python 3.11 as base image
FROM python:3.11-slim

# Install system dependencies required for rasterio and other image processing libraries
RUN apt-get update && apt-get install -y \
    gdal-bin \
    libgdal-dev \
    gcc \
    g++ \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

# Set environment variables for GDAL
ENV CPLUS_INCLUDE_PATH=/usr/include/gdal
ENV C_INCLUDE_PATH=/usr/include/gdal

# Set working directory
WORKDIR /app

# Copy only the necessary files
COPY requirements_pre.txt .
COPY src/pre-process.py src/
COPY src/s3_upload.py src/
COPY src/logger.py src/
COPY src/cloudwatch.py src/

COPY config/config_pre_process.py config/
COPY config/config_aws.py config/
COPY config/__init__.py config/

# Create necessary directories
RUN mkdir -p data/input \
    data/ofsets \
    data/processed_images/input_preprocessed \
    data/processed_images/splited_images \
    src/logs

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements_pre.txt

# Create volumes for:
# 1. Input data that needs to be processed
# 2. Processed images storage
# 3. Logs storage
VOLUME ["/app/data/input", "/app/data/processed_images", "/app/src/logs"]

# Set environment variables for AWS credentials (to be provided at runtime)
ENV AWS_ACCESS_KEY_ID=""
ENV AWS_SECRET_ACCESS_KEY=""

# Command to run the script
CMD ["python", "src/pre-process.py"]